stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy
image: docker:20.10.5
services:
  - docker:20.10.5-dind
builder:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - docker build -t some_local_build:latest .
  except:
    - main
deployer:      # This job runs in the deploy stage.
  stage: deploy
  script:
    - docker build -t $CI_REGISTRY/lisenka/netology/hello:gitlab-$CI_COMMIT_SHORT_SHA .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/lisenka/netology/hello:gitlab-$CI_COMMIT_SHORT_SHA
  only:
    - main